---
- name: reset zookeeper data
  file:
    path: "{{ zookeeper_version_data_dir }}"
    state: absent

- name: restart zookeeper
  systemd:
    name: "{{zookeeper_service_name}}"
    state: "{{ zookeeper_enabled | ternary('restarted', 'stopped') }}"
    enabled: "{{ zookeeper_enabled }}"
    daemon_reload: yes
